export const NFTContracts = {
  // ConFi is the mascot of the Conflux community.
  confi: 'cfx:acc370g3s6d56ndcp8t6gyc657rhtp0fz6ytc8j9d2',
  // The New Year Carnival Series Roast Cards are issued by Conflux Community Fun Committee during the Carnival Activity held in the Spring Festival in 2020.
  confiCard: 'cfx:accczxbt4ebbnns39k1zczgj4s397h89mjheyw8gt7',
  // ConDragon is the first DeFi+NFT+RPG game in the Conflux community.
  conDragon: 'cfx:acb3fcbj8jantg52jbg66pc21jgj2ud02pj1v4hkwn',
  // The Guardian Badge is generated by staking FC at fccfx.confluxscan.io.
  confluxGuardian: 'cfx:ach7c9fr2skv5fft98cygac0g93999z1refedecnn1',
  // Ancient Chinese God NFT
  ancientChineseGod: 'cfx:acbp6r5kpgvz3pcxax557r2xrnk4rv9f02tpkng9ne',
  // Ancient Chinese God Genesis NFT
  ancientChineseGodGenesis: 'cfx:acfpey6redpxtprhktcb78yvfg69ru69hefu7jze7r',
  // Genesis NFT is the NFT airdropped by moonswap to 1024 pilots participating in Genesis lunar landing
  moonswapGenesis: 'cfx:ace6x5ckj2d47fzsfj5pvu8uejf6hkj2denccrga1x',
  // ConHero is published by the Conflux community development team "FengYun Studio".
  conHero: 'cfx:acgjttbz35rukntbvnp6u6arx8rwwxekfyks00vr3n',
  // Longshi NFT is composed of three C-level dinosaur NFTs, which can be opened to B, a, s and SSS level dinosaur NFT.
  conDragonStone: 'cfx:aca3rsc5dexn0v0d65gbzuuvdkygmby54a0937ab68',
  // ConFi will drive the Satoshi Nakamoto spaceship to the moon on the Pizza Day.
  satoshiGift: 'cfx:aca2b2m3r6esybzn2gwprmhe692n92154y48cs0g0h',
  // Shan hai jing NFT
  shanhaijing: 'cfx:accyby39bahapc9gm7utnyve8j85htsf5j9173yt3r',
  // Shanhaiching Series Card Pack - Open through NFTBox to get a random set of beautiful Shanhaiching exotic cards
  shanhaichingSeriesCard: 'cfx:ace75v0h345vhbn9vzsg2ukkvkw65cbbvjpcvnza3e',
  // All Conflux wallet addresses that have cross-chained more than 1000 CFX from Conflux Network to BSC from March 24th 18:00 until March 29th 18:00 (GMT + 8) will be rewarded an exclusive NTF.
  shuttleflowBscNft: 'cfx:acemxe9xudprr1wu9hap6d349pa7uuc6wpjy0guwt9',
  // Cross-Chain NFT / Glory Edition is an honorary NFT launched for Conflux's first DeFi lending protocol---Flux.
  crossChainNftGloryEdition: 'cfx:acajsgt3jpfjd23gdcw8uvry7jb9ttfe6pjeha40uc',
  // Media, exchanges and ecosystem projects partners are gathering for ConFi’s birthday party themed on “Going Global”.
  happyBirthdayToConfi: 'cfx:acb5tyk4cg64em7w3gpu0u00en6bnaf7mjwr9hj3k8',
  // At the genesis of TREA's creation
  TREAGenesisFeitian: 'cfx:accfeg3rcm430khhbz09r4t38aswm5u9dezucjxjcf',
  // From March 3 at 3:00 am UTC to March 5 at 4:00 pm UTC, all participants who deposit 1,000 CFX or more to OKEx will be eligible to receive a nonfungible token.1068 total
  OKExNft: 'cfx:acg22hydxwbnf5wg6webmg84se6ukk3jkujdvm4su0',
  // To commemorate the Conflux Network's success as the third-largest decentralized network in the world during the testing phase
  // TODO
  // minerNft: 'cfx:achmupumcabzu59dj90nn400uppgy4gf2u1775528k',
  // Practitioner Medals are customized commemorative badges for participants who have reached the final stage of "Practitioner Program".
  honorOfPractitioner: 'cfx:acgugys133t7mbd277w5c1s2xcgrpknc126pdy0m85',
  // Schrödinger's box is a collection of encrypted art
  confiOfSchrodinger: 'cfx:ach6uf6tw78g1jn9k06m7t0dy80z9tc9yjc8yw32w3',
  // Three Kingdoms
  threeKingdoms: 'cfx:acepdehsmt07kcd2hspae9dashzgddrva240azrmm5',
  // EpiK Protocol Knowledge Badge
  epiKProtocolKnowledgeBadge: 'cfx:acev4c2s2ttu3jzxzsd4a2hrzsa4pfc3f6f199y5mk',
  // TODO add nft
};

export const NFTContractNames = {
  confi: {
    zh: '烤仔',
    en: 'ConFi',
  },
  confiCard: {
    zh: '烤仔卡',
    en: 'ConFi Card',
  },
  conDragon: {
    zh: 'ConDragon 恐龙',
    en: 'ConDragon',
  },
  confluxGuardian: {
    zh: '守护者勋章',
    en: 'Guardian Badge',
  },
  ancientChineseGod: {
    zh: '古国序列',
    en: 'Ancient Chinese God',
  },
  ancientChineseGodGenesis: {
    zh: '古国创世纪念卡',
    en: 'Ancient Chinese God Genesis',
  },
  moonswapGenesis: {
    zh: 'MoonSwap 创世',
    en: 'MoonSwap Genesis',
  },
  conHero: {
    zh: 'ConHero',
    en: 'ConHero',
  },
  conDragonStone: {
    zh: '龙石',
    en: 'Dragon Stone',
  },
  satoshiGift: {
    zh: "Satoshi's gift",
    en: "Satoshi's gift",
  },
  shanhaijing: {
    zh: '山海经',
    en: 'Shanhaijing',
  },
  shanhaichingSeriesCard: {
    zh: '山海经系列卡包',
    en: 'Shanhaiching Series Card Pack',
  },
  shuttleflowBscNft: {
    zh: 'ShuttleFlow-BSC',
    en: 'ShuttleFlow-BSC',
  },
  crossChainNftGloryEdition: {
    zh: '荣耀版跨链',
    en: 'Cross-Chain / Glory Edition',
  },
  happyBirthdayToConfi: {
    zh: 'Happy Birthday to ConFi',
    en: 'Happy Birthday to ConFi',
  },
  TREAGenesisFeitian: {
    zh: 'TREA创世飞天',
    en: 'TREA Genesis Feitian',
  },
  OKExNft: {
    zh: 'OKEx',
    en: 'OKEx',
  },
  // minerNft: {
  //   zh: '矿工',
  //   en: 'Miner',
  // },
  honorOfPractitioner: {
    zh: '践行者计划',
    en: 'Honor of Practitioner',
  },
  confiOfSchrodinger: {
    zh: '薛定谔的盒',
    en: 'Confi of Schrodinger',
  },
  threeKingdoms: {
    zh: '拓扑三国',
    en: 'Three Kingdoms',
  },
  epiKProtocolKnowledgeBadge: {
    zh: 'EpiK 知识徽章',
    en: 'EpiK Knowledge Badges',
  },
  // TODO add nft
};

export const NFTContractAddresses = Object.values(NFTContracts);

export const NFTNames = {
  confi: {
    '001': {
      en: 'ConFiActor',
      zh: '明星烤仔',
    },
    '002': {
      en: 'ConFi & ConKi',
      zh: '烤仔与烤喵',
    },
    '003': {
      en: 'ConFiAngel',
      zh: '天使烤仔',
    },
    '004': {
      en: 'ConFiDemon',
      zh: '恶魔烤仔',
    },
    '005': {
      en: 'ConFiMiner',
      zh: '矿工烤仔',
    },
    '006': {
      en: 'ConFiMouse',
      zh: '金鼠烤仔',
    },
    '007': {
      en: 'ConFiPhD',
      zh: '博士烤仔',
    },
    '008': {
      en: 'ConFiRapper',
      zh: '嘻哈烤仔',
    },
  },
  // ancientChineseGod: {
  //   'Pan Gu': '盘古',
  //   'Nü Wa': '女娲',
  //   'Fu Xi': '伏羲',
  //   'Sui Ren': '燧人',
  //   'Shen Nong': '神农',
  //   Yu: '禹',
  //   'Yellow Emperor': '黄帝',
  //   'Chi You': '蚩尤',
  //   'Gong Gong': '共工',
  //   'Kua Fu': '夸父',
  // },
};
